# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0
jobs:
  build-and-push:
      environment:
        DOCKER_IMAGE: dangkhoa0894/react-ci-demo
        DOCKER_TAG: latest
      executor: docker/docker
      steps:
        - setup_remote_docker
        - checkout
        - docker/check:
            docker-username: DOCKER_USER
            docker-password: DOCKER_PASSWORD
        - docker/build:
            image: $DOCKER_IMAGE
            tag: $DOCKER_TAG
        - docker/push:
            digest-path: /tmp/digest.txt
            image: my_repo/orb-test
        - run:
            command: |
              echo "Digest is: $(</tmp/digest.txt)"

workflows:
  my-pipeline:
    jobs:
      - node/test
      - build-and-push:
          filters:
            requires:
              - node/test
            branches:
              only:
                - main